name: Health Check

on:
  schedule:
    - cron: '0 * * * *' 

jobs:
  health_check: 
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.SERVICE_URL }}
          max-attempts: 3
          retry-delay: 5s