name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SHOULD_DEPLOY: ${{ github.event_name == 'push' && github.ref_name == 'main' && !contains(toJson(github.event.commits.*.message), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Print SHOULD_DEPLOY
        run: echo "SHOULD_DEPLOY=$SHOULD_DEPLOY"
      - name: Install dependencies
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Run Playwright E2E tests
        run: npm run test:e2e

      - name: Trigger deployment
        if: ${{ env.SHOULD_DEPLOY == 'true' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4 
      - name: Bump version and push tag
        if: ${{ env.SHOULD_DEPLOY == 'true'}}
        uses: anothrNick/github-tag-action@e528bc2b9628971ce0e6f823f3052d1dcd9d512c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch 
  